# Add parameters, hyperparameters and coefficients to be used by multiple models and epochs
prepare:
  split: 0.20
  seed: 20170428

featurize:
  max_features: 450
  ngrams: 1

train:
  seed: 20170428
  n_est: 50
  min_split: 2
  solver: 'newton-cg'
  criterion: 'entropy'
  kernel: 'sigmoid'